---
- name: Install Apache
  hosts: node1.example.com
  tasks:
  - name: install apache
    yum: 
      name: httpd
      state: present
  - name: start apache
    service:
      name: httpd
      state: started
  - name: Open port 80
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
...
