---
- name: Remove Apache
  hosts: node1.example.com
  tasks:
  - name: remove apache
    yum: 
      name: httpd
      state: removed
  - name: delete index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: disable port 80
    firewalld:
      service: http
      permanent: true
      state: disabled
  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
...
