---
- name: Create users
  hosts: all
  vars_files:
  - passw.yml
  tasks:
    - name: Create users
      user:
        name: "{{ item.key }}"
        comment: "{{ item.value.comment }}"
        home: "{{ item.value.home }}"
        password: "{{ item.value.password | string | password_hash('sha512') }}"
        update_password: on_create
        state: present
      loop: "{{ lookup('dict', users) }}"
...
