---
# tasks file for httpd
- name: Include vars for os family
  include_vars:
    file: "{{ ansible_os_family }}.yml"
- name: install apache
  yum: 
    name: "{{ web_service_name }}"
    state: present
  when:
    ansible_os_family == "RedHat"
  notify: 
  - start_apache
- name: creating a file index.html
  copy:
    dest: "/var/www/html/index.html"
    content: Welcome to my web server
- name: open port 80
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: 
  - restart_firewalld